services:
  kislap_web_server:
    image: nginx:latest
    container_name: kislap_web_server
    ports:
      - "80:80"
    volumes:
      - ./apps/api-service:/app
      - ./.docker/nginx/conf/local:/etc/nginx/conf.d
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - kislap_database
      - kislap_flash
      - kislap_admin
    networks:
      - kislap_subnet

  kislap_flash:
    build: ./apps/api-service
    container_name: kislap_flash
    env_file:
      - ./apps/api-service/.env
    volumes:
      - ./apps/api-service:/app
      - ./apps/api-service/tmp:/app/tmp
      - kislap_flash_go_mod:/go/pkg/mod
      - kislap_flash_go_build:/root/.cache/go-build
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      kislap_database:
        condition: service_healthy
    command: air -c /app/air.toml
    networks:
      - kislap_subnet

  kislap_admin:
    build:
      context: ./apps/web-admin
      dockerfile: Dockerfile
    container_name: kislap_admin
    restart: unless-stopped
    env_file:
      - ./apps/web-admin/.env
    ports:
      - "8000:8000"
    volumes:
      - ./apps/web-admin:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/local.ini
    depends_on:
      kislap_database:
        condition: service_healthy
    networks:
      - kislap_subnet

  kislap_database:
    image: mysql:8
    container_name: kislap_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kislap
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kislap_subnet

  kislap_adminer:
    image: adminer
    container_name: kislap_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kislap_database
    networks:
      - kislap_subnet

networks:
  kislap_subnet:
    driver: bridge

volumes:
  kislap_flash_go_mod:
  kislap_flash_go_build:
  database_data:
