services:
  kislap_web_server:
    image: nginx:alpine
    container_name: kislap_web_server
    ports:
      - "2000:2000"
    restart: always
    volumes:
      - ./apps/api-service:/app
      - ./.docker/nginx/conf/prod:/etc/nginx/conf.d
      - ./.docker/nginx/log:/var/log/nginx
    depends_on:
      - kislap_database
      - kislap_flash
      - kislap_admin
    networks:
      - kislap_subnet

  kislap_flash:
    build:
      context: ./apps/api-service
      dockerfile: Dockerfile.prod
    container_name: kislap_flash
    env_file:
      - ./apps/api-service/.env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      kislap_database:
        condition: service_healthy
    networks:
      - kislap_subnet

  kislap_admin:
    build:
      context: ./apps/web-admin
      dockerfile: Dockerfile.prod
    container_name: kislap_admin
    restart: always
    env_file:
      - ./apps/web-admin/.env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web-admin:/var/www/html
      - ./.docker/php/local.ini:/usr/local/etc/php/local.ini
    depends_on:
      kislap_database:
        condition: service_healthy
    networks:
      - kislap_subnet

  kislap_database:
    image: mysql:8
    container_name: kislap_database
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: kislap
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - kislap_subnet

  kislap_adminer:
    image: adminer
    container_name: kislap_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kislap_database
    networks:
      - kislap_subnet

networks:
  kislap_subnet:
    driver: bridge

volumes:
  database_data:
